#!/bin/bash
# Port forward to a pod in k8s

if [ "$#" -ne 3 ]; then
  echo "Usage $0 <environment> <service name> <local port:remote port>"
  exit 1
fi

environment=$1
service=$2
ports=$3

pod=$(kubectl --context "$environment" get pods | grep "$service" | head -n1 | awk '{ print $1 }')
echo $pod
kubectl --context "$environment" port-forward "$pod" "$ports"
